### ISSUE TITLE
Triangle Class - Why not use pandas.Period?

### ISSUE THREAD

**Issue by thequackdaddy** [jbogaardt/chainladder-python#11]
So perusing through this code I have a few suggestions. Gonna make a separate issue for each.

For the triangle class, why not use `pandas.Period` type for the origin labels of the pandas dataframe? The advantages are that Period already has all of the fancy math already calculated, and its pretty easy to convert an array of dates or datetimes into Periods. 

For example...

```python
import pandas as pd

dates = pd.Series(['2017-06-29', '2015-03-21', '2016-10-15',
                   '2017-12-31', '2017-01-01', '2016-12-31',
                   '2017-09-30', '2017-09-01', '2017-10-01'])
dates = pd.DatetimeIndex(dates)

pd.PeriodIndex(dates, freq='A')  # Convert dates to year ending in December periods

pd.PeriodIndex(dates, freq='A-SEP')  # Convert dates to year ending in September periods

pd.PeriodIndex(dates, freq='Q')  # Convert dates to quarter periods

pd.PeriodIndex(dates, freq='M')  # Convert dates to month periods
```

A full list of all the available options are [here](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)

**Comment by jbogaardt** [comment]
@thequackdaddy , that's pretty cool.  I wonder though whether it would break any triangle format where the origin period is just an integer, like the 'GenIns' sample.  Still, I'm much more in favor of making this real world compatible than toy example compatible and in the real world, actuaries use real time intervals.

**Comment by thequackdaddy** [comment]
Agreed. I was mainly suggesting using this as a replacement for all the string manipulation you have. 

I'm not in favor of making this format *mandatory*--integers and custom strings are fine by me--but its a very compelling use case and I would focus on that instead of all the string wrangling. He's a (small) snippet of a bunch of code that I think could be eliminated.

https://github.com/jbogaardt/chainladder-python/blob/5c711034149ae79fe9a60350d25e3cb3626892a6/chainladder/Triangle.py#L105-L130

**Comment by jbogaardt** [comment]
@thequackdaddy, I've modified Triangle.py to have origin and development stored as dates and now use pandas functionality to manage this.  It is much more robust and I am pleased with the utility of this class now.  Really appreciate your inspiration on this one, and let me know if you have thoughts to the contrary.  For now I am marking this as closed.
