### ISSUE TITLE
Triangle Class - Internal Storing of Data

### ISSUE THREAD

**Issue by thequackdaddy** [jbogaardt/chainladder-python#12]
The triangle class allows you to import data in 2 manners:

* Tabular or "long" format
* Triangle format

I would suggest that that--while you can import the data in either format, internally `Triangle` should reshape the data so that it is one of the two. I'm somewhat ambivalent which one is more appropriate--although I actually have a slight preference for the triangle format--I think. Not fully convinced one way or the other. 

My objection to having the class save it in either format is that it means that all the resulting methods/functions need to be aware if the triangle is in trabular or triangular format first, and you have to write separate code for each usecase. If we store the data internally as one, this problem is eliminated.

**Comment by jbogaardt** [comment]
@thequackdaddy , I'm not opposed to this one either, and had thought about it.  I also agree that since triangle format is how actuaries generally work with the data, we can eliminate the overhead of converting format every time people want to do something.

**Comment by jbogaardt** [comment]
Modified triangle to be stored in triangle format only.  Thanks again for the inspiration.  This allows for the removal of a bunch of technical debt while streamlining the API, for example:
dataform and data_as_triangle() are no longer necessary.
