### ISSUE TITLE
PEP8 - Lots o changes

### ISSUE THREAD

**Issue by thequackdaddy** [jbogaardt/chainladder-python#14]
Much of the code does not conform to PEP8. Fully understand this is a free tool and all, but PEP8 provides a nice (mostly) standardized way to write python. I think its unnecessary (and potentially dangerous) to make PRs for the sole purpose of major PEP8 fixes. It would make more sense to just fix the problems as the code is refactored. 

To that end, would there be objections to  having one of the CI builds just run a linter/flake8 on the diff between the PR and master? Another good encouragement tool. 

Note that most python editors I'm aware of have PEP8 style analysis/linters either built in or as easily installable plugins. Atom and spyder are 2 I use regularly and both do it very nicely.

**Comment by jbogaardt** [comment]
@thequackdaddy , have you ever used [autopep8](https://github.com/hhatto/autopep8)?  I tried it out early on, and assumed I would just convert when it became a priority.  That might have been naive, but that is where I was going.  Linters are like brocolli, I don't like them but I know they're good for me. No objection to the additional scaffolding for the project (BTW, your coverage update inspired me to add more unit tests - still not enough coverage).
I'm using atom and spyder as well and so I'll play with the pep8 guide rails there in and be more sensitive to pep8 as we continue to build/refactor.

**Comment by thequackdaddy** [comment]
Closed in #15
