### ISSUE TITLE
Ultimates is missing? 

### ISSUE THREAD

**Issue by jmatthewpeters** [jbogaardt/chainladder-python#17]
Did I miss something or is the Ultimates (method or attribute) missing from the Chainladder object?  I looked at the code for it and it doesn't seem likes it there in the same form as the documentation.  I'm happy to add it if it needs to be or change the documentation.  

Thanks
Matt

**Comment by jbogaardt** [comment]
Not sure if you are downloading the master branch or running the latest release from pypi.  It appears that the documentation on the readme link is to the master branch (which has substantial changes from the latest release).

Assuming you are using the deterministic module, the ultimates should just be a property of the chainladder object.

for example
`import chainladder as cl
import chainladder.deterministic as cld

tri = cl.Triangle(cl.load_dataset('RAA'))
print(cld.Chainladder(tri).ultimates)
`
works from the master branch

**Comment by jbogaardt** [comment]
I'll also add that on the stochastic.Chainladder, there is no ultimate, but you could do:
`cl.Chainladder(tri).full_triangle.iloc[:,-1]` to get them

**Comment by jmatthewpeters** [comment]
I had installed mine from pip and not from github.  thanks for working on this it's made my life a ton easier.

**Comment by jmatthewpeters** [comment]
Also I figured out the part I was missing was the deterministic import.  I was using the older version
