### ISSUE TITLE
Chainladder version compatible with IBM Watson 

### ISSUE THREAD

**Issue by AragondaJyosna** [jbogaardt/chainladder-python#24]
The highest Python version used by Watson Studio is 3.5. Do you have chainladder version that is compatible with one of the Watson Studio Python versions?

**Comment by jbogaardt** [comment]
Not at this time, chainladder uses python 3.6 and later, at least one conflict is the use of f-strings not supported in python 3.5.  Admittedly, that's the only conflict I can think of and f-string usage is tiny, so making it backward compatible to 3.4/3.5 shouldn't be incredibly difficult. 

I'll take a look and if it is as simple as that, I'll make chainladder 0.2.6 compatible with python 3.5.  Hoping to do a release in the next 7-10 days.

**Comment by jbogaardt** [comment]
Had enough to just push a release today.  Go ahead and try `chainladder==0.2.6`.  It's available through `pip`.  If this works for you, let me know so we can close the issue.

**Comment by AragondaJyosna** [comment]
Thank you so much, Sir, for responding so quickly with your busy schedules. 
Yes, it is working. 
Really grateful to you.
