### ISSUE TITLE
improve origin/development inference on Triangle class

### ISSUE THREAD

**Issue by jbogaardt** [jbogaardt/chainladder-python#46]
date inference relies heavily on how `pandas.to_datetime` infers date-like columns.  It is not perfect, so many date-like styles are not supported.  
```
# Create a dataframe with a bunch of date-like columns
import pandas as pd
df = pd.Series(['2019-01-15','2018-07-15','2019-05-05','2019-10-01'],
               dtype='datetime64[ns]', name='date').to_frame()
df['year'] = df['date'].dt.year
df['quarter'] = df['date'].dt.quarter
df['month'] = df['date'].dt.month
df['year_month']=df['date'].dt.strftime('%Y%m').astype(int)
df['year_quarter1']=df['year'].astype(str) + 'Q' + df['quarter'].astype(str)
df['year_quarter2']=df['year'].astype(str) + '-Q' + df['quarter'].astype(str)
df['quarter_year'] = 'Q' + df['quarter'].astype(str) + df['year'].astype(str)
df['date_as_str1'] = df['date'].dt.strftime('%Y-%m-%d')
df['date_as_str2'] = df['date'].dt.strftime('%m/%d/%Y')

# See how chainladder infers them
import chainladder as cl  

cl.Triangle.to_datetime(df, ['year','quarter']) # works, but treats quarters as month
cl.Triangle.to_datetime(df, ['year','month'])  # works
cl.Triangle.to_datetime(df, ['date'])   # works
cl.Triangle.to_datetime(df, ['year_quarter1'])  # works
cl.Triangle.to_datetime(df, ['year_quarter2'])  # works
cl.Triangle.to_datetime(df, ['date_as_str1'])  # works
cl.Triangle.to_datetime(df, ['date_as_str2'])  # works
# cl.Triangle.to_datetime(df, ['quarter_year']) # doesn't work, but should
# cl.Triangle.to_datetime(df, ['Month', 'Day', 'Year']) # doesn't work, but should
# cl.Triangle.to_datetime(df, ['Year','Month', 'Day']) # doesn't work, but should
# cl.Triangle.to_datetime(df, ['Quarter', 'Year']) # doesn't work, but probably should
```
An improvement would be to expose the `format` argument to the user, e.g. `origin_format`, `development_format` in `Triangle.__init__` to allow them to auto-override the auto-inference.

**Comment by peterdavidsonONE** [comment]
Extending this, it would be good if Period('M') type was inferred correctly.
The output of the triangle class is a period, would be nice if the input could also be a date period.
At the moment it gives an error.

**Comment by jbogaardt** [comment]
This was just resolved with [this commit](https://github.com/casact/chainladder-python/commit/9b71dfeadda122f557df05b1b21b8ea3594c7f57).

Try installing the latest `chainladder` (currently 0.5.2)

**Comment by peterdavidsonONE** [comment]
This works great.
Thanks. As soon as my python skills catch up I'll try contributing.
Cheers.

**Comment by jbogaardt** [comment]
Thanks @peterdavidsonONE, just raising issues like this helps tremendously in improving the project even if you aren't writing source code.  I appreciate you being vocal about your use cases.
