### ISSUE TITLE
json serializers for everything

### ISSUE THREAD

**Issue by jbogaardt** [jbogaardt/chainladder-python#47]
Objects should serialize nicely `to_json` and `from_json`.  This will be useful for adding RDBMS support for more sophisticated workflow management.

**Comment by peterdavidsonONE** [comment]
have you seen the dill package? this lets you serialize python objects, and works for a triangle

**Comment by jbogaardt** [comment]
@peterdavidsonONE , I have not heard much about dill.  Chainladder currently has `to_pickle` and `read_pickle` via the joblib  library.  This was chosen as it is the pickling method used by scikit-learn from which chainladder inherit its `BaseEstimator`.  That said, I am not sure if joblib is the right choice vs dill vs making it work with the standard library pickle protocol.

Ideally, we can support multiple serialization formats and this particular issue was to address JSON serialization.  My expectation is JSON will open up more opportunities that cannot be addressed by pickles. Specifically, JSON strings can be stored in a relational DB, noSQL DB, and is the protocol for communicating with Javascript and the web browser.

**Comment by peterdavidsonONE** [comment]
I was having trouble with passing pickles as I am using Dash, which no longer allows 'byte' types to be serializes. I've stumbled across dill and jsonpickle, which works quite well, e.g.
`strJSON = jsonpickle.encode(dill.dimps(aTriangle)) 
aNewTriangle = dill.loads(jsonpickle.decode(strJSON))`
I'm not sure yet how much overhead this is adding, but it required very little coding.

**Comment by jbogaardt** [comment]
Oh, that's pretty cool functionality.  Is it possible to deserialize outside of python (like in Javascript)?

I am curious if the new `to_json`, `read_json`  in chainladder support your use case.  One thing I like about the current chainladder JSON implementation is: 
1. less dependencies (uses standard library only)
2. the JSON is human-readable

**Comment by jbogaardt** [comment]
I may have answered my own question - if the JSON is not human readable, then it would be tough to deserialize outside of python.

**Comment by peterdavidsonONE** [comment]
the new to_json & read_json do in fact meet my needs -> could have saved myself a couple of hours if I'd updated the package first :)
