### ISSUE TITLE
Development fit producing incorrect result with quarterly data

### ISSUE THREAD

**Issue by allenclong** [jbogaardt/chainladder-python#51]
The ldfs fit for quarterly data are incorrect. 
Simple short example below. With n_period = 1 the ldfs should be the same as the last diagonal/row of link_ratios, regardless of average='simple' or 'volume'.  This appears to only work on the first quarter. Note that simple and volume (and regression) produce different results even with n_periods=1.

```
data = cl.load_dataset('quarterly')
data=data['paid']
print(data.link_ratio)
print(cl.Development(n_periods=1, average='simple').fit(data).ldf_)
print(cl.Development(n_periods=1, average='volume').fit(data).ldf_)
```
Example is easier to see if you run in a notebook without using print().

**Comment by jbogaardt** [comment]
Issue in determining weights for asymmetric triangles, i.e. `origin_grain != development_grain`

`Development._assign_n_periods_weight_int` needs to be written to acount for this.
```python
    def _assign_n_periods_weight_int(self, X, n_periods):
        ''' Zeros out weights depending on number of periods desired
            Only works for type(n_periods) == int
        '''
        if n_periods < 1 or n_periods >= X.shape[-2] - 1:
            return X.values*0+1
        else:
            # This section produces incorrect results for asymmetric triangles
            flip_nan = np.nan_to_num(X.values*0+1)
            k, v, o, d = flip_nan.shape
            w = np.concatenate((1-flip_nan[..., -(o-n_periods-1):, :],
                                np.ones((k, v, n_periods+1, d))), 2)*flip_nan
            return w*X.expand_dims(X.nan_triangle())
```

**Comment by allenclong** [comment]
[6551a3f](https://github.com/jbogaardt/chainladder-python/commit/6551a3fbac3fd3f0e53cf4152c404c2037cca7e5) only appears to fix when n_periods = 1. 
The above example produces the same results for n_periods = 1-4 for the first couple ldfs.
