### ISSUE TITLE
Development lag calculation is off by one quarter

### ISSUE THREAD

**Issue by allenclong** [jbogaardt/chainladder-python#55]
Importing data and creating a triangle with origin grain of 'Y' and development grain of 'Q' results in development calculation being off by 3.

Recreate:
`dict = {'state':['ST']*21, 'AY':['2017']*11 + ['2018']*7 + ['2019']*3,
        'evaluation_date':['3/31/2017','6/30/2017','9/30/2017','12/31/2017', '3/31/2018','6/30/2018','9/30/2018','12/31/2018', '3/31/2019','6/30/2019','9/30/2019'
                          , '3/31/2018','6/30/2018','9/30/2018','12/31/2018', '3/31/2019','6/30/2019','9/30/2019', '3/31/2019','6/30/2019','9/30/2019'],
        'paid': list(range(3,36,3)) + list(range(3,24,3)) + list(range(3,12,3))
       }
df = pd.DataFrame(dict)

triangle = cl.Triangle(df, 
        origin='AY',
        development=['evaluation_date'], 
        index = ['state'],
        columns = ['paid']
    )

print(triangle[triangle.development <= 6])`

Adding a zero to QuarterEnd in _period_end in chainladder/core/base.py from:
`offset = {12: pd.tseries.offsets.MonthEnd(),
                  4: pd.tseries.offsets.QuarterEnd(),
                  1: pd.tseries.offsets.YearEnd()}`
to 
`offset = {12: pd.tseries.offsets.MonthEnd(),
                  4: pd.tseries.offsets.QuarterEnd(0),
                  1: pd.tseries.offsets.YearEnd()}`
seems to fix the problem. It doesn't appear to be an issue with annual grains. I have not tested month grains.

**Comment by jbogaardt** [comment]
Running your example (from latest chainladder release), I'm not sure I see the issue.  Here is my [In]/[Out]
```python
dict = {'state':['ST']*21, 'AY':['2017']*11 + ['2018']*7 + ['2019']*3,
'evaluation_date':['3/31/2017','6/30/2017','9/30/2017','12/31/2017', '3/31/2018','6/30/2018','9/30/2018','12/31/2018', '3/31/2019','6/30/2019','9/30/2019'
, '3/31/2018','6/30/2018','9/30/2018','12/31/2018', '3/31/2019','6/30/2019','9/30/2019', '3/31/2019','6/30/2019','9/30/2019'],
'paid': list(range(3,36,3)) + list(range(3,24,3)) + list(range(3,12,3))
}
df = pd.DataFrame(dict)

triangle = cl.Triangle(df,
origin='AY',
development=['evaluation_date'],
index = ['state'],
columns = ['paid']
)
triangle
```
Origin | 3 | 6 | 9 | 12 | 15 | 18 | 21 | 24 | 27 | 30 | 33
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2017|3.00 | 6.00 | 9.00 | 12.00 | 15.00 | 18.00 | 21.00 | 24.00 | 27.00 | 30.00 | 33.00
2018|3.00 | 6.00 | 9.00 | 12.00 | 15.00 | 18.00 | 21.00 |   |   |   |  
2019|3.00 | 6.00 | 9.00
```python
triangle[triangle.development <= 6]
```

Origin | 3 | 6
-- | -- | --
2017|3.0000 | 6.0000
2018|3.0000 | 6.0000
2019|3.0000 | 6.0000

This seems correct.  Is this not what you see?  If not, can you let me know which versions of numpy and pandas you have installed?

**Comment by jbogaardt** [comment]
Actually, the latest release does not have `_period_end` in base.py.  Not sure if I already fixed this.  Can you confirm your version of chainladder as well?

**Comment by allenclong** [comment]
Yes, I can confirm. I thought I had updated, but I was using an old cached version of the library.  Sorry for the confusion.
